name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
        
    - name: Run UI Playwright tests
      run: npx playwright test tests/ui

    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-ui-html-report
        path: playwright-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-ui-report
        path: allure-results

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run API Playwright tests
      run: npx playwright test tests/api

    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-api-html-report
        path: playwright-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-api-report
        path: allure-results
